---
apiVersion: v1
kind: Service
metadata:
  labels:
    facing: front
    service: pbredirect
    type: nginx
  name: pbredirect-nginx
spec:
  ports:
    -
      name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    service: pbredirect
    type: nginx
  type: LoadBalancer
